version: "3.7"
networks:
  proteome_scout_service_network_private:
    name: proteome_scout_service_network_private
    external: false
services:
  proteome_scout_3:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_DEBUG=true
      - LDFLAGS=-L/usr/local/opt/openssl@3/lib
      - CPPFLAGS=-I/usr/local/opt/openssl@3/include
    volumes:
      - ./app:/proteome_scout-3/app
      - ./nginx_app.conf:/etc/nginx/sites-available/default
      - ./supervisor_app.conf:/etc/supervisor/conf.d/supervisor_app.conf
      - ./supervisor_app.conf:/etc/supervisor/supervisord.conf
    container_name: proteome_scout_3
    ports:
      - 80:5000
    networks:
      - proteome_scout_service_network_private


