name: Docker Build CI

on:
  push:
    branches:
    - '**'
    tags:
    - 'prod-*.*'

jobs:
  build-for-git:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Set the emv
      id: set_env
      run: echo "BUILD_PROJ=proteome-scout-3" >> $GITHUB_ENV
    - name: Set the branch name
      id: set_branch_name
      run: echo "name=branch" >> $GITHUB_OUTPUT
    - name: Extract branch name
      shell: bash
      run: echo "ghcr.io/NaegleLab/${{ env.BUILD_PROJ }}:$(echo ${GITHUB_REF##*/})"
      id: extract_branch
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build and push
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.set_branch_name.outputs.branch }}
          ghcr.io/NaegleLab/${{ env.BUILD_PROJ }}:latest
    - name: Build and push
      if: github.ref != 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.set_branch_name.outputs.branch }}
