name: Docker Build CI

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ghcr.io$/naeglelab/${{ github.repository }}:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
